In [2]:
#np is a standard annotation
import numpy as np

In [2]:
#To create a NumPy array, you can use the function np.array(). We initialize array inside square brackets[]
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [10]:
#Creating array filled with 0s and 1s
np_zero = np.zeros(3)
print(np_zero)
np_one = np.ones(2)
print(np_one)

[0. 0. 0.]
[1. 1.]


In [12]:
#Creating an array with a range of evenly spaced intervals.
#np.arrange(starting number, ending number(not included), steps)
#ending number doesn't show up, if it's odd and the step is even, last number before the odd number is shown stepping by an odd number
a_arange = np.arange(2,12,2)
b_arange = np.arange(2, 11, 2)
c_arange = np.arange(2,11, 2.5)

print(a_arange,"\n",b_arange,"\n",c_arange)

[ 2  4  6  8 10] 
 [ 2  4  6  8 10] 
 [2.  4.5 7.  9.5]


In [16]:
#We can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:
#np.linspace(starting number, ending number(included), total number)
a_lspce = np.linspace(0,10, num = 5)
print (a_lspce)
b_lspce = np.linspace(0, 14, num = 4)
print(b_lspce)

[ 0.   2.5  5.   7.5 10. ]
[ 0.          4.66666667  9.33333333 14.        ]


In [21]:
#Sorting 
arr1 = np.array([2,1,5,3,7,4])
arr2 = np.array([2,-1,5,3,-7,4])

print(np.sort(arr1),"\n",np.sort(arr2))

arr3 = np.sort(np.array([4,-1,3,7,-8]))
print(arr3)

[1 2 3 4 5 7] 
 [-7 -1  2  3  4  5]
[-8 -1  3  4  7]


In [28]:
#Concatenate np.concatenate()
a = np.array([1,-1,3,4])
b = np.array([5,6])
print(np.concatenate((a,b)))
np.sort(np.concatenate((a,b)))

[ 1 -1  3  4  5  6]


array([-1,  1,  3,  4,  5,  6])

In [41]:
#delete elements from an array
#np.delete(a,index)
a = np.array([1,2,3])
# a[0] : index
np.delete(a,0)
np.add(a,3)

array([4, 5, 6])

In [46]:
#Multi dimention arrays
multi_dim = np.array([[0,1,2,3],[4,5,6,7]])
print(multi_dim)
print(multi_dim.ndim) #dimension
print(multi_dim.size) #number of element in array
multi_dim.shape#(row, col)

[[0 1 2 3]
 [4 5 6 7]]
2
8


(2, 4)

In [51]:
multi_dim = np.array([
    [[0,1,2,3],
    [4,5,6,7]],
    [[0,2,4,6],
    [8,10,12,14]]
])
print(multi_dim.shape)#height, rows, cols
print(multi_dim.ndim)#number of dimensions
print(multi_dim.size)#number of elements

multi_dim2 = np.array([
    [[0,1,2,3],
    [4,5,6,7]],
    [[0,2,4,6],
    [8,10,12,14]],
    [[1,2,3,4],
     [1,2,3,4]]
])

print(multi_dim2.shape)
print(multi_dim2.ndim)
print(multi_dim2.size)

(2, 2, 4)
3
16
(3, 2, 4)
3
24


In [4]:
#indexing and slicing
#You may want to take a specific section of your array to use in further analysis or operations.
#in python, index always start from 0.

data = np.array([1,2,3,5,100])
print(data[3])

print(data[0:2])# index [2] isn't included

print(data[-3:]) #pick last 3 elements in the array
print(data[-2:])
print("\n")
data_2d = np.array([[1,2,10],[4,5,6]])
print(data_2d[:2,:2])# we pick the rows based on how many we specify, then specify the cols 
print(data_2d[:2,-1:])

5
[1 2]
[  3   5 100]
[  5 100]


[[1 2]
 [4 5]]
[[10]
 [ 6]]


In [78]:
#subset of an array
data = np.array([1,2,3,4])

#less than equal to 3
print(data[data<=3])

#divisible by 2
print(data[data%2 ==0])

#select elements that satisfy two conditions using the & and | operators:
print(data[(data >2) & (data < 4)])
print(data[(data == 4) | (data == 2)])

# a = 2

[1 2 3]
[2 4]
[3]
[2 4]


In [80]:
#logical operators & and | can return boolean values that specify whether or not the values in an array fullfil a certain condition
data = np.array([1,2,3,4,5,6])

gt_eq_4 = (data > 4) | (data == 4)
print(gt_eq_4)

[False False False False False False]


In [8]:
#Basic array operations

#addition
data = np.array([-1,2,3])
ones = np.ones(3,dtype=int) #creating an array of ones
dataones = data + ones # we add +1 to every element in the array
print(dataones) 

[0 3 4]


In [93]:
#substraction
#[-1,2,3]
dataones_sub = data - ones

#multiplication
dataones_mult = data * ones

#division
dataones_div = data / ones

#modulo?
dataones_mod = data % ones

print(dataones_sub,dataones_mult, dataones_div, dataones_mod)

[-2  1  2] [-1  2  3] [-1.  2.  3.] [0 0 0]


In [96]:
# sum of elements in an array
a = np.array([1,2,3,4])
print(a.sum())

#multi-dimension
b = np.array([[10,1],[3,2]])

print(b.sum(axis = 0)) # sum across columns
print(b.sum(axis = 1)) # sum across rows

10
[13  3]
[11  5]


In [99]:
# min, max, mean, and standard
a = np.array([1,2,3,4,5])

#minimun in an array
print(a.min())

#maximum of an array
print(a.max())

#mean of an array
print(a.mean())

#standard deviation of an array
print(a.std())

1
5
3.0
1.4142135623730951


In [9]:
#operations: multi - dimension array
data = np.array([[2,1],
                [3,4]])
print(data.sum(), data.max(), data.min(axis = 0), data.min(axis = 1))


10 4 [2 1] [1 3]
